### ISSUE TITLE
Cannot output when gulp.dest

### ISSUE THREAD

**Issue by vamcc** [jlouns/gulp-requirejs-optimize#11]
Hi.
I cannot get the output when using this plugin.
My gulp task is like this:

```
gulp.task('scripts', function () {
    return gulp.src('pages/web/room.js')
        .pipe(rjs({
            appDir: 'apps',
            baseUrl: 'apps',
            optimize: 'none'
        }))
        .pipe(gulp.dest('dist'));
});
```

The log is like this:

```
[11:27:24] Starting 'scripts'...
[11:27:25] Finished 'scripts' after 17 ms
```

And there is no dist folder created.Can you tell me what‘s the problem?

**Comment by jlouns** [comment]
I think your problem is in your configuration options. Are you sure you need `appDir` and/or `baseUrl`? Check out the [r.js options docs](https://github.com/jrburke/r.js/blob/master/build/example.build.js). It says that if `baseUrl` is specified, it should be relative to `appDir`, so it's going to be looking for your file in `apps/apps/room.js`. I don't know what the rest of your app looks like, but you may be fine omitting both parameters.

**Comment by vamcc** [comment]
Sorry, it's my problem. Done now. Thanks!
