### ISSUE TITLE
Performance compared to r.js CLI

### ISSUE THREAD

**Issue by drbarto** [jlouns/gulp-requirejs-optimize#18]
When running the r.js optimizer from commandline, it takes about 10 seconds to build my project. With gulp-requirejs-optimize, it takes almost 2 minutes. I'm pretty sure that my setup is flawed; it would be great if someone could have a look.

First, this is my build.js for the CLI build:

```
({
  baseUrl: 'js',
  name: 'main',
  out: 'main-built.js',
  paths: {
    qrcode: 'libs/jquery.qrcode',
    // ...
  },
  shim: {
    // ...
  }
})
```

... which I call with this command: `r.js -o build.js`

And this is my gulp task:

```
gulp.task('rjs', function() {
  return gulp.src('js/**/*.js')
    .pipe(requirejsOptimize({
      optimize: 'none',
      useStrict: true,
      baseUrl: 'js',
      name: 'main',
      out: 'main-built.js'
      paths: {
        qrcode: 'libs/jquery.qrcode',
        // ...
      },
      shim: {
        // ...
      }      
    }))
    .pipe(gulp.dest('dist'));
});
```

The only obvious difference when compared to the samples in the docs I can see is that I pass in all .js files in the directory tree instead of single files/directories.

Any hint what I might be doing wrong here?

**Comment by jlouns** [comment]
You're correct, you're seeing poor performance because you're passing in all of the .js files vs a single file. Every file that gets passed in kicks off another build, so it's taking so long because it's building your app many many times and just overwriting the result. A simple fix would be:

``` js
gulp.task('rjs', function() {
  return gulp.src('js/main.js')
    .pipe(requirejsOptimize({
      optimize: 'none',
      useStrict: true,
      baseUrl: 'js',
      name: 'main',
      out: 'main-built.js'
      paths: {
        qrcode: 'libs/jquery.qrcode',
        // ...
      },
      shim: {
        // ...
      }      
    }))
    .pipe(gulp.dest('dist'));
});
```

You can experiment with removing the `name` parameter, since the plugin should populate the `include` parameter based on the name of the file. That should be equivalent to `name` for most applications.

You only want to pass in multiple files if you want to kick off multiple different builds based on each individual js file or config file you pass in.

**Comment by drbarto** [comment]
Stupid me... of course, that fixes the problem. I was mislead by the examples which pass in multiple files. Thanks!
