### ISSUE TITLE
How to use `dir` based options

### ISSUE THREAD

**Issue by taybin** [jlouns/gulp-requirejs-optimize#21]
It looks like gulp-requirejs-optimize always passes the `out` option to requirejs.optimize().  I'd like to use the `bundlesConfigOutFile` option which only works with the `dir` option.  The documentation seems to say this should be supported, but the code looks like it doesn't support setting `dir` at all.

**Comment by jlouns** [comment]
`dir` unfortunately isn't supported due to how data is passed in and out of the plugin via gulp. This is documented in the [readme](https://github.com/jlouns/gulp-requirejs-optimize#options), but since 2.2.0 added that `bundlesConfigOutFile`, I will update it to specifically say that isn't supported as well.
